version : '3'
services :
  app:
    build: .
    container_name: app
    depends_on:
      - db
      - redis
    ports:
      - "8075:8075"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/courses
      - SPRING_DATASOURCE_USERNAME=demo
      - SPRING_DATASOURCE_PASSWORD=demo
    networks:
      - spring-docker
  db:
    image: "bitnami/postgresql:latest"
    container_name: db
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=courses
    networks:
      - spring-docker
    ports:
      - "15432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - spring-docker

volumes:
  db_data:
    driver: local
networks:
  spring-docker:
    driver: bridge